# Cloud Build configuration for deploying to Cloud Run

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/advanced-tool-agent:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/advanced-tool-agent:latest'
      - '-f'
      - 'deployment/Dockerfile'
      - '.'
    id: 'build-image'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/advanced-tool-agent:$SHORT_SHA'
    id: 'push-image'
    waitFor: ['build-image']

  # Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/advanced-tool-agent:latest'
    id: 'push-latest'
    waitFor: ['build-image']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'advanced-tool-agent'
      - '--image'
      - 'gcr.io/$PROJECT_ID/advanced-tool-agent:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GEMINI_API_KEY=${_GEMINI_API_KEY}'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
    id: 'deploy-cloud-run'
    waitFor: ['push-image']

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/advanced-tool-agent:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/advanced-tool-agent:latest'

# Substitutions for environment variables
substitutions:
  _GEMINI_API_KEY: 'your-api-key-here'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'

timeout: '1200s'
